### ISSUE TITLE
LinkedIn login popup not coming

### ISSUE THREAD

**Issue by sreenadh09** [sarfarazansari/ng4-social-login#11]
if i am already logged into linked in in another tab popup for login and allow access is not appearing.
i would like the pop up to come every time i click on sign in with linkedin. also if i am logging out here i am being logged out from other tabs ass well.

i do not see any demo for this module,could any one provide me a LinkedIn example.
Thanks

**Comment by sarfarazansari** [comment]
@sreenadh09 `ng4-social-login` plugin is using linkedin SDK.
And what you asking is default functionality of Linkedin SDK.
Linkedin JS store values in local and session storage. and Also get values from there.
So If you already logged on linkedin. It will never ask you to log in because you already logged In the same browser.

TO re-login you have to go through the different browser.

For the Demo currently, am having a very busy schedule. Whenever I got the Time I'll do it. It is already on my milestone.

I hope you understand now.
